repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # Specify the latest Ruff version
    hooks:
      # - id: ruff
      #   types: [python]
      #   args: [--fix, --exit-non-zero-on-fix]

      - id: ruff-format
        types: [python]
